### ISSUE TITLE
[BUG] Mobs froze and can't unfreeeze. 

### ISSUE THREAD

**Issue by arturek1666** [LoneDev6/Issues-ServerBooster#4] opened 2020-05-21 09:05 UTC
**Describe the bug**
For some reason the mobs don't do nothing what so ever they just stuck, even the included command to fix thoes issues dosn't help and they dont disapear and I have this now:
![image](https://user-images.githubusercontent.com/1558228/82542717-5db13080-9b4a-11ea-856f-f3086ebf7c5d.png)

**To Reproduce**
To reproduce it, is really hard the mobs just randomly specially the guardians. They just don't want to get fixed after they got frozen for no reason

**Expected behavior**

**Info (please complete the following information):**
 - Server version: Paper 1.15.2
 - Client version: 1.15.2
 - Plugin version: 1.0.31

(IMPORTANT:
I am not sure if that's 100% fault of the plugin but still can't seem to be able to unfreze thoes mobs

Edit by LoneDev:
Duplicates: 
https://github.com/LoneDev6/Issues-ServerBooster/issues/11
https://github.com/LoneDev6/Issues-ServerBooster/issues/6

**Comment by arturek1666** [comment] 2020-05-21 12:25
This issue was caused most likly by an paper then plugin closing.

**Comment by LoneDev6** [comment] 2020-05-21 14:07
What do you mean? was it a paper bug?
is it fixed now?

**Comment by arturek1666** [comment] 2020-05-21 14:40
Well everything was fine with your plugin, but after engine update i use SSpigot with is premium source however it uses paperspigot source etc, and my guess it is engine fault so I close this issue as I don't think it's you plugin fault.

**Comment by LoneDev6** [comment] 2020-06-01 12:03
Please send here your paper build and if you get any error in console

**Comment by arturek1666** [comment] 2020-06-06 13:18
The issue for me was resolved closing.

**Comment by LoneDev6** [comment] 2020-06-22 12:44
> 
> 
> The issue for me was resolved closing.

Resolved with paper/spigot update?

**Comment by LoneDev6** [comment] 2020-07-06 10:47
Seems Minecraft 1.16.1 is not affected by this problem, right?

**Comment by arturek1666** [comment] 2020-07-08 09:43
Not tested yet. Will do it today.

**Comment by MeesterMaarten** [comment] 2020-07-13 20:38
I run ServerBooster: 1.0.34 on Paper-1.16.1: build-90 [Jul 12, 2020] and don't have this problem!

**Comment by MeesterMaarten** [comment] 2020-07-13 21:59
> I run ServerBooster: 1.0.34 on Paper-1.16.1: build-90 [Jul 12, 2020] and don't have this problem!

Never mind... Players are starting to report "**frozen**" Mobs in the world. The problem remains!

![image1](https://user-images.githubusercontent.com/46909512/87357740-d5a54100-c564-11ea-8070-993d3bc1c8bf.png)
![image0](https://user-images.githubusercontent.com/46909512/87357743-d6d66e00-c564-11ea-80f7-38cb54b8b08b.png)
![unknown](https://user-images.githubusercontent.com/46909512/87357747-d76f0480-c564-11ea-9c6d-35a595e82e93.png)

**Comment by LoneDev6** [comment] 2020-07-14 12:30
Thanks today I will do more tests with 1.16.1 and I hope to find a bypass for this problem

**Comment by LoneDev6** [comment] 2020-07-14 13:15
Let me know if latest update fixes this problem and if you got any error/lag from the new update.
Thanks

**Comment by frogglen** [comment] 2020-07-14 15:22
if it's of any use i found a solution
start the server by disabling the entity optimization options by placing sample worlds.
when the server starts, put back the worlds you use and reload the plugin. Done there are no more freeze mobs

**Comment by LoneDev6** [comment] 2020-07-14 17:04
> 
> 
> if it's of any use i found a solution
> start the server by disabling the entity optimization options by placing sample worlds.
> when the server starts, put back the worlds you use and reload the plugin. Done there are no more freeze mobs

mhhh i doubt this works, I think it's just a coincidence.

Anyway let me know if latest update fixed the issue

**Comment by MeesterMaarten** [comment] 2020-07-14 20:00
The problem is not solved in Paper-1.16.1: build-91 and the new 1.0.35 version ... Unfortunately!

Players are still reporting "**frozen**" Mobs in the world. These do disappear after the player has **relogged**!

These mobs are also **invisible** to other players in the same area.

Notice: Players also need to delete there "**config_optimize_entities.yml**" to get the new "fix-ghost-entities: true" setting!

CPU Is a little higher, but it is not immediately noticeable and therefore no problem!

![2020-07-14_21 44 08](https://user-images.githubusercontent.com/46909512/87470169-b10ca000-c61c-11ea-9735-d8f179b8749e.png)

**Comment by LoneDev6** [comment] 2020-07-15 09:49
Mhhh.. damn, Well I have to investigate more on this as I don't have idea how to trigger this problem.
Basically I tried to fly fast from an area to another multiple times until I saw frozen mobs, then I added my fix (fix-ghost-entities: true) and problem seemed to be solved, but as you say it's not.

I don't have idea why these mobs are not removed by the client, maybe it's just slow? My fix removes old entities from the client but has a little delay to avoid packet spam, maybe you have to wait some seconds.

How many players does your server has?

**Comment by LoneDev6** [comment] 2020-07-15 10:30
Edit: I published a new update, seems I identified the cause, it's a desyncronization of the entities data from client to server.
My new fix should work fine now, let me know

**Comment by DomSathanas** [comment] 2020-07-16 21:36
For me the new update don't work. My players sometimes can't see the entities, they need to relog in the server to see them again.
When i put the fix-ghost-entities on true, don't solve the problem and cause a lot of lag in my server. When a toggle that option in false, go so much better. 
This new update fixes the problem of frozen mobs, but instead the ghost entities can attack the players or they can't see the mobs (for example, pets like cats) and make the problem worst.

**Comment by LoneDev6** [comment] 2020-07-17 09:16
Sadly this is a downside of the fix I added to remove fake entities generated by desyncronization from client entity list and server entity list.

Today I will make a lot of tests and code a new bypass for this problem, Spigot/Paper added a new patch in recent updates which breaks serverbooster so I had to implement this stuff
I hope to manage to make a proper fix

**Comment by MeesterMaarten** [comment] 2020-07-22 07:26
Problem has been solved in the latest version. No more Reports about frozen or invisible Mobs.

This topic can be closed. Thanks @LoneDev6!

**Closed** 2020-07-22 08:29 UTC
Labels: bug
