### ISSUE TITLE
[BUG] Asynchronous Chunk get entities call (Purpur/Tuinity 1.16.4)

### ISSUE THREAD

**Issue by arturek1666** [LoneDev6/Issues-ServerBooster#33] opened 2020-11-13 08:15 UTC
**Describe the bug**
There is a spam with errors from serverbooster:
https://gist.github.com/arturek1666/9c8bb4e1a3707140c44a9974406cf76b

**To Reproduce**
The error just randomly shows through the day.

**Expected behavior**
There should be no spam errors in console

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.4
 - Client version: 1.16.4
 - Plugin version: 1.0.49.

**Comment by NESTOWL** [comment] 2020-11-15 00:04
I confirm.
When connecting to the server, an exception is thrown.
![cmd_NZnBJAaDcb](https://user-images.githubusercontent.com/45520187/99159637-3c8f5e00-26ef-11eb-8530-09ee7b863314.png)

**Comment by LoneDev6** [comment] 2020-11-16 13:32
Please try on Spigot or Paper, seems Tuinity is checking if plugins use getEntities function in async threads which is breaking the plugin.

**Comment by istarengwa** [comment] 2020-12-11 02:27
Hello, sorry for not opening another ticket, having the exact same problem. I always use purpur and your plugin worked before   :/

**Comment by LoneDev6** [comment] 2020-12-11 10:50
Hello! no problem.
Can you ask purpur author if they have changed the getEntities function behaviour? Seems they added a check to avoid async call, but i need to call it async.
Send them this error:
```
[00:46:21] [Craft Scheduler Thread - 7 - ServerBooster/FATAL]: Thread Craft Scheduler Thread - 7 - ServerBooster failed thread check for reason: Asynchronous Chunk get entities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.4.jar:git-Tuinity-"1d4c8fc"]
	at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:1023) ~[patched_1.16.4.jar:git-Tuinity-"1d4c8fc"]
	at net.minecraft.server.v1_16_R3.World.getEntities(World.java:1171) ~[patched_1.16.4.jar:git-Tuinity-"1d4c8fc"]
	at net.minecraft.server.v1_16_R3.World.getEntities(World.java:1155) ~[patched_1.16.4.jar:git-Tuinity-"1d4c8fc"]
	at dev.lone.serverbooster.c.h.b.b.a(SourceFile:163) ~[?:?]
	at dev.lone.serverbooster.c.h.b.b.a(SourceFile:153) ~[?:?]
	at dev.lone.serverbooster.c.h.b.b.a(SourceFile:146) ~[?:?]
	at dev.lone.serverbooster.c.h.b.b.a(SourceFile:82) ~[?:?]
	at dev.lone.serverbooster.c.h.b.b.run(SourceFile:63) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Tuinity-"1d4c8fc"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.4.jar:git-Tuinity-"1d4c8fc"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Tuinity-"1d4c8fc"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```


Anyway please try using Paper or Spigot and let me know if the issue is still there. If not this is a Purpur incompatibility we have to address somehow.

**Comment by istarengwa** [comment] 2020-12-11 22:34
Hello, I just tried the paper version, and it works fine, no errors.

**Comment by istarengwa** [comment] 2020-12-11 22:59
I created a github error message on their github, here is the link, if you can help me explain to them because I did not understand everything ^^

https://github.com/pl3xgaming/Purpur/issues/117

**Comment by BillyGalbreath** [comment] 2020-12-12 01:06
The async catcher is in place because this method (like most others) are not thread safe, and can be really destructive. There are plans to add the async catcher upstream as far as CB itself, so it is advised to adapt now rather than scramble for a solution later ;)

**Comment by BillyGalbreath** [comment] 2020-12-13 00:44
Looks like the feature _only_ made it up to Spigot. CB was left out.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/628435a80b4e69e07735824489f15c9689a411d7

**Comment by mikroskeem** [comment] 2020-12-13 02:09
inb4 "hey guys please use craftbukkit to continue using my plugin". lol.

**Comment by LoneDev6** [comment] 2020-12-14 17:34
Fixed in the new update

**Closed by LoneDev6** 2020-12-14 17:34 UTC
Labels: Unofficial fork, bug

**Comment by arturek1666** [comment] 2020-12-16 23:38
The issue is gone but a new one has arrived will post different issue :)
